### PR TITLE
Piwi code  injected in head section since amd method was not working.

### PR DESCRIPTION
**Pull request by jobcespedes**
Workaround (could be one solution?) to https://github.com/bmbrands/moodle-local_analytics/issues/11

### CODE REVIEW

**Comment by defrox** [comment]
I would suggest to replace http: and https: from the piwik url, and to approve this PR.
Great Job!

**Comment by lucaboesch** [comment]
Yes, I second that.
That would be great.

**Comment by xDaizu** [comment]
After a week banging my head against the wall, he code in this patch FINALLY made it work. I am so grateful! 😃

**Comment by lucaboesch** [comment]
Yeah, @xDaizu that's why it would be great if this pull request was finally accepted to the master branch.

**Comment by lucaboesch** [comment]
Bas, great to see you have a job at Moodle now. You need to update your profile there https://moodle.org/user/profile.php?id=907814. Also, would you mind integrating this pull request?

**Pull request merged**
